CREATE DATABASE CampaignInformationManagement
ON PRIMARY (NAME = 'CampaignInformationManagement_data', FILENAME = 'D:\eProject\CampaignInformationManagement_data.mdf', SIZE = 10)
LOG ON (NAME = 'CampaignInformationManagements_log', FILENAME = 'D:\eProject\CampaignInformationManagement_log.ldf', SIZE = 10, FILEGROWTH = 1)
GO

USE CampaignInformationManagement
GO

CREATE TABLE ROLES
(
	ROLEID INT PRIMARY KEY,
	ROLENAME VARCHAR(50) NULL,
	DESCRIPTION VARCHAR(200) NULL,
)
GO

CREATE TABLE USERS
(
	USERID VARCHAR(50) PRIMARY KEY,
	USERNAME VARCHAR(50) UNIQUE NOT NULL,
	PASSWORD VARCHAR(50) NULL,
	ROLEID INT NULL FOREIGN KEY REFERENCES ROLES(ROLEID) ON DELETE CASCADE ON UPDATE CASCADE
)
GO

CREATE TABLE CAMPAIGNS
(
	CAMPAIGNID VARCHAR(50) PRIMARY KEY,
	TYPEOFCAMPAIGN VARCHAR(50) NULL,
	STARTDAY DATETIME NULL,
	ENDDAY DATETIME NULL
)
GO

CREATE TABLE PRODUCTS
(
	PRODUCTID VARCHAR(50) PRIMARY KEY,
	PRODUCTNAME VARCHAR(50) NULL,
	DESCRIPTION VARCHAR(200) NULL,
)
GO

CREATE TABLE MANAGECAMS
(
	MANAGEID INT PRIMARY KEY,
	USERID VARCHAR(50) NULL FOREIGN KEY REFERENCES USERS(USERID) ON DELETE CASCADE ON UPDATE CASCADE,
	CAMPAIGNID VARCHAR(50) NULL FOREIGN KEY REFERENCES CAMPAIGNS(CAMPAIGNID) ON DELETE CASCADE ON UPDATE CASCADE,
	PRODUCTID VARCHAR(50) NULL FOREIGN KEY REFERENCES PRODUCTS(PRODUCTID) ON DELETE CASCADE ON UPDATE CASCADE
)
GO

CREATE TABLE PRICES
(
	PRICEID INT PRIMARY KEY,
	PRICE INT NULL,
	STARTDAY DATETIME NULL,
	ENDDAY DATETIME NULL
)
GO

CREATE TABLE PRODUCTS_PRICES
(
	ID INT PRIMARY KEY,
	PRODUCTID VARCHAR(50) NULL FOREIGN KEY REFERENCES PRODUCTS(PRODUCTID) ON DELETE CASCADE ON UPDATE CASCADE,
	PRICEID INT NULL FOREIGN KEY REFERENCES PRICES(PRICEID) ON DELETE CASCADE ON UPDATE CASCADE
)
GO

CREATE TABLE ESTIMATES
(
	CAMPAIGNID VARCHAR(50) NULL FOREIGN KEY REFERENCES CAMPAIGNS(CAMPAIGNID) ON DELETE CASCADE ON UPDATE CASCADE,
	BUDGET INT NULL,
	TARGET INT NULL,
	VARIANCEALLOWED INT NULL
)
GO

CREATE TABLE REALITYS
(
	CAMPAIGNID VARCHAR(50) NULL FOREIGN KEY REFERENCES CAMPAIGNS(CAMPAIGNID) ON DELETE CASCADE ON UPDATE CASCADE,
	SUMQUANTITY INT NULL,
	SUMBUDGET INT NULL
)
GO

CREATE TABLE EXCHANGES
(
	CAMPAIGNID VARCHAR(50) NULL FOREIGN KEY REFERENCES CAMPAIGNS(CAMPAIGNID) ON DELETE CASCADE ON UPDATE CASCADE,
	SALEDAY DATETIME NULL,
	QUANTITY INT NULL
)
GO

INSERT INTO ROLES(ROLEID, ROLENAME, DESCRIPTION) VALUES (1, 'Admin', 'System Management'), (2, 'Manager', 'Campaign Management'), (3, 'Reporter', 'Campaign Reporter')
GO

INSERT INTO USERS(USERID, USERNAME, PASSWORD, ROLEID) values('Admin', 'admin', 'admin' , 1)
GO