/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.CampaignsDAO;
import dao.ProductsDAO;
import dao.UsersDAO;
import java.awt.Color;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;

/**
 *
 * @author USER
 */
public class Admin extends javax.swing.JFrame {
    CampaignsDAO campaigndao = new CampaignsDAO();
    ProductsDAO productdao = new ProductsDAO();
    UsersDAO userdao = new UsersDAO();

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        setLocationRelativeTo(null);
        Campaign campaign = new Campaign();
        campaign.setTitle("Campaign");
        createView(campaign);
        Information();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBg = new javax.swing.JPanel();
        pnLeft = new javax.swing.JPanel();
        pnLogOut = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnCampaign = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbCampaign = new javax.swing.JLabel();
        pnProduct = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbProduct = new javax.swing.JLabel();
        pnUser = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        pnChangePassword = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pnRight = new javax.swing.JPanel();
        lbCountCampaign = new javax.swing.JLabel();
        lbCountProduct = new javax.swing.JLabel();
        lbCountUser = new javax.swing.JLabel();
        lbImgCampaign = new javax.swing.JLabel();
        lbImgProduct = new javax.swing.JLabel();
        lbImgUser = new javax.swing.JLabel();
        dpMain = new javax.swing.JDesktopPane();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        pnBg.setBackground(new java.awt.Color(255, 255, 255));
        pnBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnLeft.setBackground(new java.awt.Color(54, 33, 89));
        pnLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnLogOut.setBackground(new java.awt.Color(54, 33, 89));
        pnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnLogOutMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_logout_rounded_left_filled_20px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Log Out");

        javax.swing.GroupLayout pnLogOutLayout = new javax.swing.GroupLayout(pnLogOut);
        pnLogOut.setLayout(pnLogOutLayout);
        pnLogOutLayout.setHorizontalGroup(
            pnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLogOutLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnLogOutLayout.setVerticalGroup(
            pnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLogOutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnLeft.add(pnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 270, 60));

        pnCampaign.setBackground(new java.awt.Color(85, 65, 118));
        pnCampaign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnCampaignMouseClicked(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_strike_filled_20px_1.png"))); // NOI18N

        lbCampaign.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCampaign.setForeground(new java.awt.Color(204, 204, 204));
        lbCampaign.setText("Campaign");

        javax.swing.GroupLayout pnCampaignLayout = new javax.swing.GroupLayout(pnCampaign);
        pnCampaign.setLayout(pnCampaignLayout);
        pnCampaignLayout.setHorizontalGroup(
            pnCampaignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCampaignLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbCampaign, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnCampaignLayout.setVerticalGroup(
            pnCampaignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCampaignLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCampaignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCampaign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnLeft.add(pnCampaign, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 270, 60));

        pnProduct.setBackground(new java.awt.Color(64, 43, 100));
        pnProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnProductMouseClicked(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_car_insurance_card_filled_20px.png"))); // NOI18N

        lbProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbProduct.setForeground(new java.awt.Color(204, 204, 204));
        lbProduct.setText("Product");

        javax.swing.GroupLayout pnProductLayout = new javax.swing.GroupLayout(pnProduct);
        pnProduct.setLayout(pnProductLayout);
        pnProductLayout.setHorizontalGroup(
            pnProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProductLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnProductLayout.setVerticalGroup(
            pnProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnLeft.add(pnProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 270, 60));

        pnUser.setBackground(new java.awt.Color(64, 43, 100));
        pnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnUserMouseClicked(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_employee_card_20px.png"))); // NOI18N

        lbUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbUser.setForeground(new java.awt.Color(204, 204, 204));
        lbUser.setText("User");

        javax.swing.GroupLayout pnUserLayout = new javax.swing.GroupLayout(pnUser);
        pnUser.setLayout(pnUserLayout);
        pnUserLayout.setHorizontalGroup(
            pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUserLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbUser, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnUserLayout.setVerticalGroup(
            pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnLeft.add(pnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 270, 60));

        pnChangePassword.setBackground(new java.awt.Color(54, 33, 89));
        pnChangePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnChangePasswordMouseClicked(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_key_20px.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Change Password");

        javax.swing.GroupLayout pnChangePasswordLayout = new javax.swing.GroupLayout(pnChangePassword);
        pnChangePassword.setLayout(pnChangePasswordLayout);
        pnChangePasswordLayout.setHorizontalGroup(
            pnChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChangePasswordLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnChangePasswordLayout.setVerticalGroup(
            pnChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnChangePasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnLeft.add(pnChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 270, 60));
        pnLeft.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 230, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_user_male_circle_filled_100px.png"))); // NOI18N
        pnLeft.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 120, 100));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Admin");
        pnLeft.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 120, 40));

        pnBg.add(pnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 700));

        pnRight.setBackground(new java.awt.Color(122, 72, 221));
        pnRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCountCampaign.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCountCampaign.setForeground(new java.awt.Color(255, 255, 255));
        lbCountCampaign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCountCampaign.setText("0");
        pnRight.add(lbCountCampaign, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 50, 40));

        lbCountProduct.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCountProduct.setForeground(new java.awt.Color(255, 255, 255));
        lbCountProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCountProduct.setText("0");
        pnRight.add(lbCountProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 50, 40));

        lbCountUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCountUser.setForeground(new java.awt.Color(255, 255, 255));
        lbCountUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCountUser.setText("0");
        pnRight.add(lbCountUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 50, 40));

        lbImgCampaign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImgCampaign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_strike_filled_100px.png"))); // NOI18N
        pnRight.add(lbImgCampaign, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 110, 100));

        lbImgProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImgProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_car_insurance_card_filled_100px.png"))); // NOI18N
        pnRight.add(lbImgProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 110, 80));

        lbImgUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImgUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_employee_card_100px.png"))); // NOI18N
        pnRight.add(lbImgUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 80, 100));

        pnBg.add(pnRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 730, 190));

        javax.swing.GroupLayout dpMainLayout = new javax.swing.GroupLayout(dpMain);
        dpMain.setLayout(dpMainLayout);
        dpMainLayout.setHorizontalGroup(
            dpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        dpMainLayout.setVerticalGroup(
            dpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        pnBg.add(dpMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 730, 450));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(85, 65, 118));
        jLabel15.setText("X");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        pnBg.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 20, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnCampaignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnCampaignMouseClicked
        // TODO add your handling code here:
        setColor(pnCampaign);
        resetColor(pnProduct);
        resetColor(pnUser);
        Campaign campaign = new Campaign();
        campaign.setTitle("Campaign");
        createView(campaign);
        Information();
    }//GEN-LAST:event_pnCampaignMouseClicked

    private void pnProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnProductMouseClicked
        // TODO add your handling code here:
        resetColor(pnCampaign);
        setColor(pnProduct);
        resetColor(pnUser);
        Product product = new Product();
        product.setTitle("Product");
        createView(product);
        Information();
    }//GEN-LAST:event_pnProductMouseClicked

    private void pnUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnUserMouseClicked
        // TODO add your handling code here:
        resetColor(pnCampaign);
        resetColor(pnProduct);
        setColor(pnUser);
        User user = new User();
        user.setTitle("User");
        createView(user);
        Information();
    }//GEN-LAST:event_pnUserMouseClicked

    private void pnChangePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnChangePasswordMouseClicked
        // TODO add your handling code here:
        new ChangepasswordloginFrm().setVisible(true);
    }//GEN-LAST:event_pnChangePasswordMouseClicked

    private void pnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnLogOutMouseClicked
        // TODO add your handling code here:
        new LoginFrm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnLogOutMouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel15MouseClicked

    void setColor(JPanel panel){
        panel.setBackground(new Color(85,65,118));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(64,43,100));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    private void createView(JInternalFrame Inf) {
        JInternalFrame[] arrI = null;
        arrI = dpMain.getAllFrames();
        boolean check = true;
        for(JInternalFrame a : arrI){
            if(a.getTitle().equals(Inf.getTitle())){
                check = false;
            }
        }
        if(check){
            dpMain.add(Inf);
            arrI = dpMain.getAllFrames();
        }
        
        for(JInternalFrame a : arrI){
            if(a.getTitle().equals(Inf.getTitle())){
                a.setVisible(true);
                break;
            }
            else{
                a.setVisible(false);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbCampaign;
    private javax.swing.JLabel lbCountCampaign;
    private javax.swing.JLabel lbCountProduct;
    private javax.swing.JLabel lbCountUser;
    private javax.swing.JLabel lbImgCampaign;
    private javax.swing.JLabel lbImgProduct;
    private javax.swing.JLabel lbImgUser;
    private javax.swing.JLabel lbProduct;
    private javax.swing.JLabel lbUser;
    private javax.swing.JPanel pnBg;
    private javax.swing.JPanel pnCampaign;
    private javax.swing.JPanel pnChangePassword;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnLogOut;
    private javax.swing.JPanel pnProduct;
    private javax.swing.JPanel pnRight;
    private javax.swing.JPanel pnUser;
    // End of variables declaration//GEN-END:variables

    private void Information() {
        lbCountCampaign.setText(String.valueOf(campaigndao.readAll().size()));
        lbCountProduct.setText(String.valueOf(productdao.readAll().size()));
        lbCountUser.setText(String.valueOf(userdao.readAll().size()-1));
    }
}
