/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.CampaignsDAO;
import dto.Campaigns;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class CampaignsInf extends javax.swing.JInternalFrame {
    CampaignsDAO dao = null;
    int rowSelected = -1;

    /**
     * Creates new form CampaignsInf
     */
    public CampaignsInf() {
        initComponents();
        dao = new CampaignsDAO();
        loadTableTest(dao.readAll());
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        spTest = new javax.swing.JScrollPane();
        tbTest = new javax.swing.JTable();
        pnTest = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setVisible(true);

        spTest.setBackground(new java.awt.Color(255, 255, 255));

        tbTest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTestMouseClicked(evt);
            }
        });
        spTest.setViewportView(tbTest);

        lb1.setText("jLabel1");

        lb2.setText("jLabel2");

        lb3.setText("jLabel3");

        lb4.setText("jLabel4");

        bt1.setText("jButton1");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt2.setText("jButton2");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt3.setText("jButton3");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        bt4.setText("jButton4");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTestLayout = new javax.swing.GroupLayout(pnTest);
        pnTest.setLayout(pnTestLayout);
        pnTestLayout.setHorizontalGroup(
            pnTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTestLayout.createSequentialGroup()
                .addGroup(pnTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTestLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(bt1)
                        .addGap(18, 18, 18)
                        .addComponent(bt2)
                        .addGap(18, 18, 18)
                        .addComponent(bt3)
                        .addGap(18, 18, 18)
                        .addComponent(bt4))
                    .addGroup(pnTestLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(pnTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb2)
                            .addComponent(lb1)
                            .addComponent(lb3)
                            .addComponent(lb4))
                        .addGap(89, 89, 89)
                        .addGroup(pnTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnTestLayout.setVerticalGroup(
            pnTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTestLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb1))
                .addGap(18, 18, 18)
                .addGroup(pnTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb2))
                .addGap(18, 18, 18)
                .addGroup(pnTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb3))
                .addGap(18, 18, 18)
                .addGroup(pnTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(pnTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt4)
                    .addComponent(bt3)
                    .addComponent(bt2)
                    .addComponent(bt1))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(pnTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTest, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        try {
            // TODO add your handling code here:
            String a = tf1.getText().trim();
            String b = tf2.getText().trim();
            Date c = new SimpleDateFormat("dd/MM/yyyy").parse(tf3.getText().trim());
            Date d = new SimpleDateFormat("dd/MM/yyyy").parse(tf4.getText().trim());
            Campaigns s = new Campaigns(a, b, c, d);
            if (dao.create(s) != null) {
                JOptionPane.showMessageDialog(this, "Thanh Cong");
                loadTableTest(dao.readAll());
                rowSelected = -1;
            } else {
                JOptionPane.showMessageDialog(this, "That Bai");
            }
        } catch (ParseException ex) {
            Logger.getLogger(CampaignsInf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        tf1.setEditable(true);
        tf1.setText("");
        tf2.setText("");
        tf3.setText("");
        tf4.setText("");
        lb1.setText("CAMPAIGN ID");
        lb2.setText("TYPE OF CAMPAIGN");
        lb3.setText("START DAY");
        lb4.setText("END DAY");
        bt1.setText("CREATE");
        bt2.setText("REFRESH");
        bt3.setText("UPDATE");
        bt4.setText("DELETE");
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        rowSelected = tbTest.getSelectedRow();
        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(this, "Hay chon hang");
        } else {
            try {
                String a = (String) tbTest.getValueAt(rowSelected, 0);
                String b = tf2.getText().trim();
                Date c = new SimpleDateFormat("dd/MM/yyyy").parse(tf3.getText().trim());
                Date d = new SimpleDateFormat("dd/MM/yyyy").parse(tf4.getText().trim());
                Campaigns u = new Campaigns(a, b, c, d);
                if (dao.update(u) != null) {
                    JOptionPane.showMessageDialog(this, "Update Thanh Cong");
                    loadTableTest(dao.readAll());
                } else {
                    JOptionPane.showMessageDialog(this, "Update That Bai");
                }
            } catch (ParseException ex) {
                Logger.getLogger(CampaignsInf.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        // TODO add your handling code here:
        rowSelected = tbTest.getSelectedRow();
        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(this, "Hay chon hang");
        } else {
            String a = (String) tbTest.getValueAt(rowSelected, 0);
            if (dao.delete(a)) {
                JOptionPane.showMessageDialog(this, "Delete Thanh Cong");
                loadTableTest(dao.readAll());
            } else {
                JOptionPane.showMessageDialog(this, "Delete That Bai");
            }
        }
    }//GEN-LAST:event_bt4ActionPerformed

    private void tbTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTestMouseClicked
        // TODO add your handling code here:
        rowSelected = tbTest.getSelectedRow();
        String a = (String) tbTest.getValueAt(rowSelected, 0);
        String b = (String) tbTest.getValueAt(rowSelected, 1);
        Date c = (Date) tbTest.getValueAt(rowSelected, 2);
        Date d = (Date) tbTest.getValueAt(rowSelected, 3);

        tf1.setText(a);
        tf1.setEditable(false);
        tf2.setText(b);
        tf3.setText(String.valueOf(c));
        tf4.setText(String.valueOf(d));
    }//GEN-LAST:event_tbTestMouseClicked
private void loadTableTest(List<Campaigns> readAll) {
        Vector column = new Vector();
        column.add("CAMPAIGN ID");
        column.add("TYPE OF CAMPAIGN");
        column.add("START DAY");
        column.add("END DAY");
        Vector rows = new Vector();
        for (Campaigns u : readAll) {
            Vector row = new Vector();
            row.add(u.getCampaignid());
            row.add(u.getTypeofcampaign());
            row.add(u.getStartday());
            row.add(u.getEndday());
            rows.add(row);
        }
        tbTest.setModel(new DefaultTableModel(rows, column));
        tbTest.updateUI();
        spTest.setViewportView(this.tbTest);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JPanel pnTest;
    private javax.swing.JScrollPane spTest;
    private javax.swing.JTable tbTest;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    // End of variables declaration//GEN-END:variables
}
