/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.UsersDAO;
import dto.Users;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class ChangepasswordFrm extends javax.swing.JFrame {

    UsersDAO usersdao = null;

    /**
     * Creates new form ChangepasswordFrm
     */
    public ChangepasswordFrm() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        usersdao = new UsersDAO();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbOldpassword = new javax.swing.JLabel();
        lbNewpassword = new javax.swing.JLabel();
        lbConfirmnewpassword = new javax.swing.JLabel();
        btApply = new javax.swing.JButton();
        lbUsername = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        pfOldpassword = new javax.swing.JPasswordField();
        pfNewpassword = new javax.swing.JPasswordField();
        pfConfirmnewpassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbOldpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbOldpassword.setText("Old password");

        lbNewpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbNewpassword.setText("New password");

        lbConfirmnewpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbConfirmnewpassword.setText("Confirm new password");

        btApply.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btApply.setText("Apply");
        btApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApplyActionPerformed(evt);
            }
        });

        lbUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbUsername.setText("Username");

        tfUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        pfOldpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        pfNewpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        pfConfirmnewpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btApply)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbConfirmnewpassword)
                            .addGap(18, 18, 18)
                            .addComponent(pfConfirmnewpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbUsername)
                                .addComponent(lbOldpassword)
                                .addComponent(lbNewpassword))
                            .addGap(84, 84, 84)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                .addComponent(pfOldpassword)
                                .addComponent(pfNewpassword)))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(lbUsername))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addComponent(lbOldpassword))
                    .addComponent(pfOldpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNewpassword)
                    .addComponent(pfNewpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConfirmnewpassword)
                    .addComponent(pfConfirmnewpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btApply)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApplyActionPerformed
        // TODO add your handling code here:
        String username = tfUsername.getText().trim();
        String password = pfOldpassword.getText().trim();
        String newpassword1 = pfNewpassword.getText().trim();
        String newpassword2 = pfConfirmnewpassword.getText().trim();
        
        Users u = new UsersDAO().readByUsername(username);
        if (u != null) {
            if (u.getPassword().equals(password) && (newpassword1.equals(newpassword2))) {
                usersdao.update(new Users(u.getUserid(), u.getUsername(), newpassword1, u.getRoleid()));
                JOptionPane.showMessageDialog(this, "Thanh Cong");
                new LoginFrm().setVisible(true);
                this.dispose();
            } else if (!u.getPassword().equals(password)) {
                JOptionPane.showMessageDialog(this, "Password is not valid");
                pfOldpassword.setText("");
                pfNewpassword.setText("");
                pfConfirmnewpassword.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Nhap lai MK moi ko dung");
                pfOldpassword.setText("");
                pfNewpassword.setText("");
                pfConfirmnewpassword.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Username is not exit");
            tfUsername.setText("");
            pfOldpassword.setText("");
            pfNewpassword.setText("");
            pfConfirmnewpassword.setText("");
        }
    }//GEN-LAST:event_btApplyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangepasswordFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangepasswordFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangepasswordFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangepasswordFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangepasswordFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btApply;
    private javax.swing.JLabel lbConfirmnewpassword;
    private javax.swing.JLabel lbNewpassword;
    private javax.swing.JLabel lbOldpassword;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPasswordField pfConfirmnewpassword;
    private javax.swing.JPasswordField pfNewpassword;
    private javax.swing.JPasswordField pfOldpassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
