/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.EstimatesDAO;
import dao.RealitysDAO;
import dto.Estimates;
import dto.Realitys;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Estimate extends javax.swing.JInternalFrame {

    EstimatesDAO estimatedao = null;
    RealitysDAO realitydao = null;
    String campaignid = new Manager().campaignid;

    /**
     * Creates new form Estimate
     */
    public Estimate() {
        initComponents();
        estimatedao = new EstimatesDAO();
        realitydao = new RealitysDAO();
        javax.swing.plaf.InternalFrameUI ui = this.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ui).setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBg = new javax.swing.JPanel();
        tfBudget = new javax.swing.JTextField();
        tfQuantity = new javax.swing.JTextField();
        btApplyBudget = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfVarianceAllowed = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfRealityBudget = new javax.swing.JTextField();
        btApplyEstimate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(730, 450));

        pnBg.setBackground(new java.awt.Color(255, 255, 255));
        pnBg.setPreferredSize(new java.awt.Dimension(730, 450));
        pnBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfBudget.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(85, 65, 118)));
        tfBudget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfBudgetMouseClicked(evt);
            }
        });
        pnBg.add(tfBudget, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 130, -1));

        tfQuantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(85, 65, 118)));
        tfQuantity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfQuantityMouseClicked(evt);
            }
        });
        pnBg.add(tfQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 130, -1));

        btApplyBudget.setBackground(new java.awt.Color(54, 33, 89));
        btApplyBudget.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btApplyBudget.setForeground(new java.awt.Color(255, 255, 255));
        btApplyBudget.setText("Apply");
        btApplyBudget.setPreferredSize(new java.awt.Dimension(80, 30));
        btApplyBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApplyBudgetActionPerformed(evt);
            }
        });
        pnBg.add(btApplyBudget, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(85, 65, 118));
        jLabel2.setText("Budget ($)");
        pnBg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(85, 65, 118));
        jLabel3.setText("Quantity");
        pnBg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        tfVarianceAllowed.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(85, 65, 118)));
        tfVarianceAllowed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfVarianceAllowedMouseClicked(evt);
            }
        });
        pnBg.add(tfVarianceAllowed, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 130, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(85, 65, 118));
        jLabel4.setText("Variance Allowed (%)");
        pnBg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(85, 65, 118));
        jLabel5.setText("Budget ($)");
        pnBg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        tfRealityBudget.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(85, 65, 118)));
        tfRealityBudget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfRealityBudgetMouseClicked(evt);
            }
        });
        pnBg.add(tfRealityBudget, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 130, -1));

        btApplyEstimate.setBackground(new java.awt.Color(54, 33, 89));
        btApplyEstimate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btApplyEstimate.setForeground(new java.awt.Color(255, 255, 255));
        btApplyEstimate.setText("Apply");
        btApplyEstimate.setPreferredSize(new java.awt.Dimension(80, 30));
        btApplyEstimate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApplyEstimateActionPerformed(evt);
            }
        });
        pnBg.add(btApplyEstimate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Estimate");
        pnBg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 60, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Reality");
        pnBg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBg, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBg, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfBudgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfBudgetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBudgetMouseClicked

    private void tfQuantityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfQuantityMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantityMouseClicked

    private void btApplyBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApplyBudgetActionPerformed
        if (tfRealityBudget.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please complete all information");
        } else {
            int budget = Integer.parseInt(tfRealityBudget.getText().trim());
            for (Realitys rr : realitydao.readAll()) {
                if (rr.getCampaignid().equals(campaignid)) {
                    Realitys r = new Realitys(rr.getCampaignid(), rr.getSumquantity(), rr.getSumbudget() + budget);
                    realitydao.update(r);
                }
            }
            JOptionPane.showMessageDialog(null, "Success");
            tfRealityBudget.setText("");
        }
    }//GEN-LAST:event_btApplyBudgetActionPerformed

    private void tfVarianceAllowedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfVarianceAllowedMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tfVarianceAllowedMouseClicked

    private void tfRealityBudgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfRealityBudgetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRealityBudgetMouseClicked

    private void btApplyEstimateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApplyEstimateActionPerformed
        // TODO add your handling code here:
        if (tfBudget.getText().trim().equals("") || tfQuantity.getText().trim().equals("") || tfVarianceAllowed.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please complete all information");
        } else {
            int budget = Integer.parseInt(tfBudget.getText().trim());
            int target = Integer.parseInt(tfQuantity.getText().trim());
            int varianceallowed = Integer.parseInt(tfVarianceAllowed.getText().trim());
            Estimates e = new Estimates(campaignid, budget, target, varianceallowed);
            if (estimatedao.update(e) != null) {
                JOptionPane.showMessageDialog(null, "Success");
                tfBudget.setText("");
                tfQuantity.setText("");
                tfVarianceAllowed.setText("");
            }
        }
    }//GEN-LAST:event_btApplyEstimateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btApplyBudget;
    private javax.swing.JButton btApplyEstimate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pnBg;
    private javax.swing.JTextField tfBudget;
    private javax.swing.JTextField tfQuantity;
    private javax.swing.JTextField tfRealityBudget;
    private javax.swing.JTextField tfVarianceAllowed;
    // End of variables declaration//GEN-END:variables
}
