/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.CampaignsDAO;
import dao.EstimatesDAO;
import dao.ExchangesDAO;
import dao.ManagecamsDAO;
import dao.PricesDAO;
import dao.Products_PricesDAO;
import dao.RealitysDAO;
import dto.Campaigns;
import dto.Estimates;
import dto.Exchanges;
import dto.Managecams;
import dto.Prices;
import dto.Products_Prices;
import dto.Realitys;
import java.awt.Color;
import java.awt.Graphics;
import java.util.Date;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;

/**
 *
 * @author USER
 */
public class Manager extends javax.swing.JFrame {

    ManagecamsDAO managedao = null;
    EstimatesDAO estimatedao = null;
    PricesDAO pricedao = null;
    Products_PricesDAO ppdao = null;
    ExchangesDAO exchangedao = null;
    RealitysDAO realitydao = null;
    CampaignsDAO campaigndao = null;
    String userid = new LoginFrm().userids;
    String campaignid;
    String productid;

    /**
     * Creates new form Manager
     */
    public Manager() {
        initComponents();
        setLocationRelativeTo(null);
        managedao = new ManagecamsDAO();
        estimatedao = new EstimatesDAO();
        pricedao = new PricesDAO();
        ppdao = new Products_PricesDAO();
        exchangedao = new ExchangesDAO();
        realitydao = new RealitysDAO();
        campaigndao = new CampaignsDAO();
        for (Managecams mm : managedao.readAll()) {
            if (mm.getUserid().equals(userid)) {
                campaignid = mm.getCampaignid();
                productid = mm.getProductid();
            }
        }
        Information();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        pnLeft = new javax.swing.JPanel();
        pnLogOut = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnExchange = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbTransaction = new javax.swing.JLabel();
        pnPrice = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        pnEstimate = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbUpdateEstimateBudget = new javax.swing.JLabel();
        pnChangePassword = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pnRight = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbEstimateQuantity = new javax.swing.JLabel();
        lbEstimateBudget = new javax.swing.JLabel();
        lbRealityBudget = new javax.swing.JLabel();
        lbRealityQuantity = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        btUpdate = new javax.swing.JButton();
        dpMain = new javax.swing.JDesktopPane(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.setColor(Color.WHITE);
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        jLabel15 = new javax.swing.JLabel();
        lbEndday = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbCampaign = new javax.swing.JLabel();
        lbTofc = new javax.swing.JLabel();
        lbProduct = new javax.swing.JLabel();
        lbStartday = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnLeft.setBackground(new java.awt.Color(54, 33, 89));
        pnLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnLogOut.setBackground(new java.awt.Color(54, 33, 89));
        pnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnLogOutMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_logout_rounded_left_filled_20px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Log Out");

        javax.swing.GroupLayout pnLogOutLayout = new javax.swing.GroupLayout(pnLogOut);
        pnLogOut.setLayout(pnLogOutLayout);
        pnLogOutLayout.setHorizontalGroup(
            pnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLogOutLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnLogOutLayout.setVerticalGroup(
            pnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLogOutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnLeft.add(pnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 270, 60));

        pnExchange.setBackground(new java.awt.Color(85, 65, 118));
        pnExchange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnExchangeMouseClicked(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_currency_exchange_20px.png"))); // NOI18N

        lbTransaction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTransaction.setForeground(new java.awt.Color(204, 204, 204));
        lbTransaction.setText("Transaction");

        javax.swing.GroupLayout pnExchangeLayout = new javax.swing.GroupLayout(pnExchange);
        pnExchange.setLayout(pnExchangeLayout);
        pnExchangeLayout.setHorizontalGroup(
            pnExchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnExchangeLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnExchangeLayout.setVerticalGroup(
            pnExchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnExchangeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnExchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnLeft.add(pnExchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 270, 60));

        pnPrice.setBackground(new java.awt.Color(64, 43, 100));
        pnPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnPriceMouseClicked(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_price_tag_usd_20px.png"))); // NOI18N

        lbPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbPrice.setForeground(new java.awt.Color(204, 204, 204));
        lbPrice.setText("Price");

        javax.swing.GroupLayout pnPriceLayout = new javax.swing.GroupLayout(pnPrice);
        pnPrice.setLayout(pnPriceLayout);
        pnPriceLayout.setHorizontalGroup(
            pnPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPriceLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnPriceLayout.setVerticalGroup(
            pnPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPriceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnLeft.add(pnPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 270, 60));

        pnEstimate.setBackground(new java.awt.Color(64, 43, 100));
        pnEstimate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnEstimateMouseClicked(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_test_passed_20px.png"))); // NOI18N

        lbUpdateEstimateBudget.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbUpdateEstimateBudget.setForeground(new java.awt.Color(204, 204, 204));
        lbUpdateEstimateBudget.setText("Update Estimate Budget");

        javax.swing.GroupLayout pnEstimateLayout = new javax.swing.GroupLayout(pnEstimate);
        pnEstimate.setLayout(pnEstimateLayout);
        pnEstimateLayout.setHorizontalGroup(
            pnEstimateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEstimateLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbUpdateEstimateBudget, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnEstimateLayout.setVerticalGroup(
            pnEstimateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnEstimateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnEstimateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbUpdateEstimateBudget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnLeft.add(pnEstimate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 270, 60));

        pnChangePassword.setBackground(new java.awt.Color(54, 33, 89));
        pnChangePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnChangePasswordMouseClicked(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_key_20px.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Change Password");

        javax.swing.GroupLayout pnChangePasswordLayout = new javax.swing.GroupLayout(pnChangePassword);
        pnChangePassword.setLayout(pnChangePasswordLayout);
        pnChangePasswordLayout.setHorizontalGroup(
            pnChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChangePasswordLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnChangePasswordLayout.setVerticalGroup(
            pnChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnChangePasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnLeft.add(pnChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 270, 60));
        pnLeft.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 230, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_user_male_circle_filled_100px.png"))); // NOI18N
        pnLeft.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 120, 100));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Manager");
        pnLeft.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 120, 40));

        bg.add(pnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 700));

        pnRight.setBackground(new java.awt.Color(122, 72, 221));
        pnRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Estimate :");
        pnRight.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 73, 65, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Reality :");
        pnRight.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Budget");
        pnRight.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Quantity");
        pnRight.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        lbEstimateQuantity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbEstimateQuantity.setForeground(new java.awt.Color(204, 51, 0));
        lbEstimateQuantity.setText("0");
        pnRight.add(lbEstimateQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 62, 40));

        lbEstimateBudget.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbEstimateBudget.setForeground(new java.awt.Color(204, 51, 0));
        lbEstimateBudget.setText("0");
        pnRight.add(lbEstimateBudget, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 60, 40));

        lbRealityBudget.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbRealityBudget.setForeground(new java.awt.Color(204, 51, 0));
        lbRealityBudget.setText("0");
        pnRight.add(lbRealityBudget, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 130, 70));

        lbRealityQuantity.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbRealityQuantity.setForeground(new java.awt.Color(204, 51, 0));
        lbRealityQuantity.setText("0");
        pnRight.add(lbRealityQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 130, 70));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("TOTAL($)");
        pnRight.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 160, 50));

        lbTotal.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbTotal.setForeground(new java.awt.Color(204, 51, 0));
        lbTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTotal.setText("0");
        pnRight.add(lbTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 230, 60));

        btUpdate.setText("Update");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });
        pnRight.add(btUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 100, 30));

        bg.add(pnRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 730, 190));

        javax.swing.GroupLayout dpMainLayout = new javax.swing.GroupLayout(dpMain);
        dpMain.setLayout(dpMainLayout);
        dpMainLayout.setHorizontalGroup(
            dpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        dpMainLayout.setVerticalGroup(
            dpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        bg.add(dpMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 730, 450));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(85, 65, 118));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("X");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        bg.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 30, 30));

        lbEndday.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbEndday.setForeground(new java.awt.Color(204, 51, 0));
        lbEndday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.add(lbEndday, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 90, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(54, 33, 89));
        jLabel17.setText("CAMPAIGN ID");
        bg.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(54, 33, 89));
        jLabel18.setText("TYPE OF CAMPAIGN");
        bg.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(54, 33, 89));
        jLabel19.setText("PRODUCT");
        bg.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(54, 33, 89));
        jLabel20.setText("START DAY");
        bg.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(54, 33, 89));
        jLabel21.setText("END DAY");
        bg.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, -1));

        lbCampaign.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCampaign.setForeground(new java.awt.Color(204, 51, 0));
        lbCampaign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.add(lbCampaign, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 80, 20));

        lbTofc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTofc.setForeground(new java.awt.Color(204, 51, 0));
        lbTofc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.add(lbTofc, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 100, 20));

        lbProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbProduct.setForeground(new java.awt.Color(204, 51, 0));
        lbProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.add(lbProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 70, 20));

        lbStartday.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbStartday.setForeground(new java.awt.Color(204, 51, 0));
        lbStartday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.add(lbStartday, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 90, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnLogOutMouseClicked
        // TODO add your handling code here:
        new LoginFrm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnLogOutMouseClicked

    private void pnExchangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnExchangeMouseClicked
        // TODO add your handling code here:
        setColor(pnExchange);
        resetColor(pnPrice);
        resetColor(pnEstimate);
        Exchange exchange = new Exchange();
        exchange.setTitle("Exchange");
        createView(exchange);
        Information();
    }//GEN-LAST:event_pnExchangeMouseClicked

    private void pnPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnPriceMouseClicked
        // TODO add your handling code here:
        resetColor(pnExchange);
        setColor(pnPrice);
        resetColor(pnEstimate);
        Price price = new Price();
        price.setTitle("Price");
        createView(price);
        Information();
    }//GEN-LAST:event_pnPriceMouseClicked

    private void pnEstimateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnEstimateMouseClicked
        // TODO add your handling code here:
        resetColor(pnExchange);
        resetColor(pnPrice);
        setColor(pnEstimate);
        Estimate estimate = new Estimate();
        estimate.setTitle("Estimate");
        createView(estimate);
        Information();
    }//GEN-LAST:event_pnEstimateMouseClicked

    private void pnChangePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnChangePasswordMouseClicked
        // TODO add your handling code here:
        new ChangepasswordloginFrm().setVisible(true);
    }//GEN-LAST:event_pnChangePasswordMouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        // TODO add your handling code here:
        Information();
    }//GEN-LAST:event_btUpdateActionPerformed

    void setColor(JPanel panel) {
        panel.setBackground(new Color(85, 65, 118));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(64, 43, 100));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    private void createView(JInternalFrame Inf) {
        JInternalFrame[] arrI = null;
        arrI = dpMain.getAllFrames();
        boolean check = true;
        for (JInternalFrame a : arrI) {
            if (a.getTitle().equals(Inf.getTitle())) {
                check = false;
            }
        }
        if (check) {
            dpMain.add(Inf);
            arrI = dpMain.getAllFrames();
        }

        for (JInternalFrame a : arrI) {
            if (a.getTitle().equals(Inf.getTitle())) {
                a.setVisible(true);
                break;
            } else {
                a.setVisible(false);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btUpdate;
    private javax.swing.JDesktopPane dpMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbCampaign;
    private javax.swing.JLabel lbEndday;
    private javax.swing.JLabel lbEstimateBudget;
    private javax.swing.JLabel lbEstimateQuantity;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbProduct;
    private javax.swing.JLabel lbRealityBudget;
    private javax.swing.JLabel lbRealityQuantity;
    private javax.swing.JLabel lbStartday;
    private javax.swing.JLabel lbTofc;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbTransaction;
    private javax.swing.JLabel lbUpdateEstimateBudget;
    private javax.swing.JPanel pnChangePassword;
    private javax.swing.JPanel pnEstimate;
    private javax.swing.JPanel pnExchange;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnLogOut;
    private javax.swing.JPanel pnPrice;
    private javax.swing.JPanel pnRight;
    // End of variables declaration//GEN-END:variables

    private void Information() {
        for (Estimates es : estimatedao.readAll()) {
            if (es.getCampaignid().equals(campaignid)) {
                String estimatebudget = String.valueOf(es.getBudget());
                lbEstimateBudget.setText(estimatebudget);
                String estimatequantity = String.valueOf(es.getTarget());
                lbEstimateQuantity.setText(estimatequantity);
            }
        }
        for (Realitys re : realitydao.readAll()) {
            if (re.getCampaignid().equals(campaignid)) {
                String realitybudget = String.valueOf(re.getSumbudget());
                lbRealityBudget.setText(realitybudget);
                String realityquantity = String.valueOf(re.getSumquantity());
                lbRealityQuantity.setText(realityquantity);
            }
        }
        int total = 0;
        for (Exchanges e : exchangedao.readAll()) {
            for (Products_Prices pp : ppdao.readAll()) {
                if (pp.getProductid().equals(productid)) {
                    for (Prices p : pricedao.readAll()) {
                        if ((p.getPriceid() == pp.getPriceid()) && ((e.getSaleday().after(p.getStartday())||e.getSaleday().equals(p.getStartday()))&& e.getSaleday().before(p.getEndday()))) {
                            total = total + p.getPrice() * e.getQuantity();
                        }
                    }
                }
            }
            lbTotal.setText(String.valueOf(total));
        }
        
        String typeofcampaign;
        Date startday;
        Date endday;
        for(Campaigns c : campaigndao.readAll()){
            if(c.getCampaignid().equals(campaignid)){
                typeofcampaign = c.getTypeofcampaign();
                startday = c.getStartday();
                endday = c.getEndday();
                lbCampaign.setText(campaignid);
                lbTofc.setText(typeofcampaign);
                lbProduct.setText(productid);
                lbStartday.setText(startday.toString());
                lbEndday.setText(endday.toString());
            }
        }
    }
}
