/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ProductsDAO;
import dto.Products;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Product extends javax.swing.JInternalFrame {

    ProductsDAO dao = null;
    int rowSelected = -1;

    /**
     * Creates new form Product
     */
    public Product() {
        initComponents();
        dao = new ProductsDAO();
        loadTableProduct(dao.readAll());
        javax.swing.plaf.InternalFrameUI ui = this.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ui).setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBg = new javax.swing.JPanel();
        spProduct = new javax.swing.JScrollPane();
        tbProduct = new javax.swing.JTable();
        tfProductid = new javax.swing.JTextField();
        tfProductname = new javax.swing.JTextField();
        tfDescription = new javax.swing.JTextField();
        btCreate = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(730, 450));

        pnBg.setBackground(new java.awt.Color(255, 255, 255));
        pnBg.setPreferredSize(new java.awt.Dimension(730, 450));
        pnBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spProduct.setBackground(new java.awt.Color(255, 255, 255));
        spProduct.setBorder(null);

        tbProduct.setAutoCreateRowSorter(true);
        tbProduct.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tbProduct.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbProduct.setGridColor(new java.awt.Color(255, 255, 255));
        tbProduct.setRowHeight(25);
        tbProduct.setSelectionBackground(new java.awt.Color(122, 72, 221));
        tbProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProductMouseClicked(evt);
            }
        });
        spProduct.setViewportView(tbProduct);

        pnBg.add(spProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 564, 290));

        tfProductid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(85, 65, 118)));
        pnBg.add(tfProductid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 130, -1));

        tfProductname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(85, 65, 118)));
        pnBg.add(tfProductname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 130, -1));

        tfDescription.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(85, 65, 118)));
        pnBg.add(tfDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 130, -1));

        btCreate.setText("Create");
        btCreate.setPreferredSize(new java.awt.Dimension(80, 30));
        btCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateActionPerformed(evt);
            }
        });
        pnBg.add(btCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 20, -1, -1));

        btReset.setText("Reset");
        btReset.setPreferredSize(new java.awt.Dimension(80, 30));
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        pnBg.add(btReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 20, -1, -1));

        btUpdate.setText("Update");
        btUpdate.setPreferredSize(new java.awt.Dimension(80, 30));
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });
        pnBg.add(btUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 20, -1, -1));

        btDelete.setText("Delete");
        btDelete.setPreferredSize(new java.awt.Dimension(80, 30));
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        pnBg.add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 20, 79, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(85, 65, 118));
        jLabel2.setText("Product ID");
        pnBg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(85, 65, 118));
        jLabel3.setText("Product Name");
        pnBg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(85, 65, 118));
        jLabel4.setText("Description");
        pnBg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBg, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBg, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProductMouseClicked
        // TODO add your handling code here:
        rowSelected = tbProduct.getSelectedRow();
        String productid = (String) tbProduct.getValueAt(rowSelected, 0);
        String productname = (String) tbProduct.getValueAt(rowSelected, 1);
        String description = (String) tbProduct.getValueAt(rowSelected, 2);

        tfProductid.setText(productid);
        tfProductid.setEditable(false);
        tfProductname.setText(productname);
        tfDescription.setText(description);
    }//GEN-LAST:event_tbProductMouseClicked

    private void btCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateActionPerformed
        // TODO add your handling code here:
        if (tfProductid.getText().trim().equals("") || tfProductname.getText().trim().equals("") || tfDescription.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please complete all information");
        } else {
            String productid = tfProductid.getText().trim();
            String productname = tfProductname.getText().trim();
            String description = tfDescription.getText().trim();
            Products p = new Products(productid, productname, description);
            if (dao.readByProductid(productid) != null) {
                JOptionPane.showMessageDialog(null, "ID already exists");
            } else if (dao.create(p) != null) {
                JOptionPane.showMessageDialog(null, "Success");
                loadTableProduct(dao.readAll());
                tfProductid.setText("");
                tfProductname.setText("");
                tfDescription.setText("");
                rowSelected = -1;
            }
        }
    }//GEN-LAST:event_btCreateActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:
        tfProductid.setEditable(true);
        tfProductid.setText("");
        tfProductname.setText("");
        tfDescription.setText("");
        rowSelected = -1;
    }//GEN-LAST:event_btResetActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        // TODO add your handling code here:
        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(null, "Please select the row");
        } else if (tfProductname.getText().trim().equals("") || tfDescription.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please complete all information");
        } else {
            String productid = (String) tbProduct.getValueAt(rowSelected, 0);
            String productname = tfProductname.getText().trim();
            String description = tfDescription.getText().trim();
            Products p = new Products(productid, productname, description);
            if (dao.update(p) != null) {
                JOptionPane.showMessageDialog(null, "Success");
                loadTableProduct(dao.readAll());
                tfProductid.setEditable(true);
                tfProductid.setText("");
                tfProductname.setText("");
                tfDescription.setText("");
                rowSelected = -1;
            }
        }
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(null, "Please select the row");
        } else {
            String productid = (String) tbProduct.getValueAt(rowSelected, 0);
            if (dao.delete(productid)) {
                JOptionPane.showMessageDialog(null, "Success");
                loadTableProduct(dao.readAll());
                tfProductid.setEditable(true);
                tfProductid.setText("");
                tfProductname.setText("");
                tfDescription.setText("");
                rowSelected = -1;
            }
        }
    }//GEN-LAST:event_btDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCreate;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel pnBg;
    private javax.swing.JScrollPane spProduct;
    private javax.swing.JTable tbProduct;
    private javax.swing.JTextField tfDescription;
    private javax.swing.JTextField tfProductid;
    private javax.swing.JTextField tfProductname;
    // End of variables declaration//GEN-END:variables

    private void loadTableProduct(List<Products> readAll) {
        Vector column = new Vector();
        column.add("ID");
        column.add("NAME");
        column.add("DESCRIPTION");
        Vector rows = new Vector();
        for (Products pp : readAll) {
            Vector row = new Vector();
            row.add(pp.getProductid());
            row.add(pp.getProductname());
            row.add(pp.getDescription());
            rows.add(row);
        }
        tbProduct.setModel(new DefaultTableModel(rows, column));
        tbProduct.updateUI();
        spProduct.setViewportView(this.tbProduct);
    }
}
