/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.UsersDAO;
import dto.Users;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class UserInf extends javax.swing.JInternalFrame {

    UsersDAO dao = null;
    int rowSelected = -1;

    /**
     * Creates new form UserInf
     */
    public UserInf() {
        initComponents();
        dao = new UsersDAO();
        loadTableTest(dao.readAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTest = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        spTest = new javax.swing.JScrollPane();
        tbTest = new javax.swing.JTable();

        lb1.setText("jLabel1");

        lb2.setText("jLabel2");

        lb3.setText("jLabel3");

        lb4.setText("jLabel4");

        bt1.setText("jButton1");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt2.setText("jButton2");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt3.setText("jButton3");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        bt4.setText("jButton4");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTestLayout = new javax.swing.GroupLayout(pnTest);
        pnTest.setLayout(pnTestLayout);
        pnTestLayout.setHorizontalGroup(
            pnTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTestLayout.createSequentialGroup()
                .addGroup(pnTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTestLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(bt1)
                        .addGap(18, 18, 18)
                        .addComponent(bt2)
                        .addGap(18, 18, 18)
                        .addComponent(bt3)
                        .addGap(18, 18, 18)
                        .addComponent(bt4))
                    .addGroup(pnTestLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(pnTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb2)
                            .addComponent(lb1)
                            .addComponent(lb3)
                            .addComponent(lb4))
                        .addGap(89, 89, 89)
                        .addGroup(pnTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTestLayout.setVerticalGroup(
            pnTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTestLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb1))
                .addGap(18, 18, 18)
                .addGroup(pnTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb2))
                .addGap(18, 18, 18)
                .addGroup(pnTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb3))
                .addGap(18, 18, 18)
                .addGroup(pnTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(pnTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt4)
                    .addComponent(bt3)
                    .addComponent(bt2)
                    .addComponent(bt1))
                .addGap(21, 21, 21))
        );

        tbTest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTestMouseClicked(evt);
            }
        });
        spTest.setViewportView(tbTest);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spTest)
                    .addComponent(pnTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(spTest, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        String a = tf1.getText().trim();
        String b = tf2.getText().trim();
        String c = tf3.getText().trim();
        int d = Integer.parseInt(tf4.getText().trim());
        Users s = new Users(a, b, c, d);
        if (dao.create(s) != null) {
            JOptionPane.showMessageDialog(this, "Thanh Cong");
            loadTableTest(dao.readAll());
            rowSelected = -1;
        } else {
            JOptionPane.showMessageDialog(this, "That Bai");
        }
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        tf1.setEditable(true);
        tf1.setText("");
        tf2.setText("");
        tf3.setText("");
        tf4.setText("");
        lb1.setText("USER ID");
        lb2.setText("USERNAME");
        lb3.setText("PASSWORD");
        lb4.setText("ROLEID");
        bt1.setText("CREATE");
        bt2.setText("REFRESH");
        bt3.setText("UPDATE");
        bt4.setText("DELETE");
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        rowSelected = tbTest.getSelectedRow();
        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(this, "Hay chon hang");
        } else {
            String a = (String) tbTest.getValueAt(rowSelected, 0);
            String b = tf2.getText().trim();
            String c = tf3.getText().trim();
            int d = Integer.parseInt(tf4.getText().trim());
            Users u = new Users(a, b, c, d);
            if (dao.update(u) != null) {
                JOptionPane.showMessageDialog(this, "Update Thanh Cong");
                loadTableTest(dao.readAll());
            } else {
                JOptionPane.showMessageDialog(this, "Update That Bai");
            }
        }
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        // TODO add your handling code here:
        rowSelected = tbTest.getSelectedRow();
        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(this, "Hay chon hang");
        } else {
            String a = (String) tbTest.getValueAt(rowSelected, 0);
            if (dao.delete(a)) {
                JOptionPane.showMessageDialog(this, "Delete Thanh Cong");
                loadTableTest(dao.readAll());
            } else {
                JOptionPane.showMessageDialog(this, "Delete That Bai");
            }
        }
    }//GEN-LAST:event_bt4ActionPerformed

    private void tbTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTestMouseClicked
        // TODO add your handling code here:
        rowSelected = tbTest.getSelectedRow();
        String a = (String) tbTest.getValueAt(rowSelected, 0);
        String b = (String) tbTest.getValueAt(rowSelected, 1);
        String c = (String) tbTest.getValueAt(rowSelected, 2);
        int d = (int) tbTest.getValueAt(rowSelected, 3);

        tf1.setText(String.valueOf(a));
        tf1.setEditable(false);
        tf2.setText(b);
        tf3.setText(c);
        tf4.setText(String.valueOf(d));
    }//GEN-LAST:event_tbTestMouseClicked

    private void loadTableTest(List<Users> readAll) {
        Vector column = new Vector();
        column.add("USER ID");
        column.add("USERNAME");
        column.add("PASSWORD");
        column.add("ROLEID");
        Vector rows = new Vector();
        for (Users u : readAll) {
            Vector row = new Vector();
            row.add(u.getUserid());
            row.add(u.getUsername());
            row.add(u.getPassword());
            row.add(u.getRoleid());
            rows.add(row);
        }
        tbTest.setModel(new DefaultTableModel(rows, column));
        tbTest.updateUI();
        spTest.setViewportView(this.tbTest);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JPanel pnTest;
    private javax.swing.JScrollPane spTest;
    private javax.swing.JTable tbTest;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    // End of variables declaration//GEN-END:variables
}
